-- First, ensure categories exist with proper slugs
INSERT INTO categories (name, slug, description) VALUES 
  ('Légumes', 'legumes', 'Légumes frais du terroir marocain'),
  ('Fruits', 'fruits', 'Fruits de saison juteux et savoureux'),
  ('Salades', 'salades', 'Salades et légumes verts croquants'),
  ('Herbes', 'herbes', 'Herbes fraîches et épices aromatiques')
ON CONFLICT (slug) DO NOTHING;

-- Insert all products with proper categorization
INSERT INTO products (name, slug, category_id, price, unit, description, origin, is_active) VALUES
-- Légumes
('Artichaud', 'artichaud', (SELECT id FROM categories WHERE slug = 'legumes'), 15.00, 'kg', 'Artichaud frais et tendre', 'Maroc', true),
('Artichaud Beldi', 'artichaud-beldi', (SELECT id FROM categories WHERE slug = 'legumes'), 18.00, 'kg', 'Artichaud beldi traditionnel', 'Maroc', true),
('Asperge', 'asperge', (SELECT id FROM categories WHERE slug = 'legumes'), 45.00, 'kg', 'Asperges fraîches et croquantes', 'Maroc', true),
('Aubergine', 'aubergine', (SELECT id FROM categories WHERE slug = 'legumes'), 8.00, 'kg', 'Aubergines violettes brillantes', 'Maroc', true),
('Brocoli', 'brocoli', (SELECT id FROM categories WHERE slug = 'legumes'), 12.00, 'kg', 'Brocoli vert et nutritif', 'Maroc', true),
('Cardon', 'cardon', (SELECT id FROM categories WHERE slug = 'legumes'), 10.00, 'kg', 'Cardon frais du terroir', 'Maroc', true),
('Carotte', 'carotte', (SELECT id FROM categories WHERE slug = 'legumes'), 6.00, 'kg', 'Carottes douces et croquantes', 'Maroc', true),
('Champignon', 'champignon', (SELECT id FROM categories WHERE slug = 'legumes'), 25.00, 'kg', 'Champignons frais de Paris', 'Maroc', true),
('Chou-fleur', 'chou-fleur', (SELECT id FROM categories WHERE slug = 'legumes'), 8.00, 'kg', 'Chou-fleur blanc et ferme', 'Maroc', true),
('Chou Rouge', 'chou-rouge', (SELECT id FROM categories WHERE slug = 'legumes'), 7.00, 'kg', 'Chou rouge coloré et croquant', 'Maroc', true),
('Chou Vert', 'chou-vert', (SELECT id FROM categories WHERE slug = 'legumes'), 6.00, 'kg', 'Chou vert tendre', 'Maroc', true),
('Citrouille Rouge', 'citrouille-rouge', (SELECT id FROM categories WHERE slug = 'legumes'), 5.00, 'kg', 'Citrouille rouge savoureuse', 'Maroc', true),
('Concombre', 'concombre', (SELECT id FROM categories WHERE slug = 'legumes'), 4.00, 'kg', 'Concombres frais et rafraîchissants', 'Maroc', true),
('Courgette', 'courgette', (SELECT id FROM categories WHERE slug = 'legumes'), 7.00, 'kg', 'Courgettes vertes tendres', 'Maroc', true),
('Endive', 'endive', (SELECT id FROM categories WHERE slug = 'legumes'), 20.00, 'kg', 'Endives blanches et croquantes', 'Maroc', true),
('Épinard', 'epinard', (SELECT id FROM categories WHERE slug = 'legumes'), 8.00, 'kg', 'Épinards verts et nutritifs', 'Maroc', true),
('Épinard Pottes', 'epinard-pottes', (SELECT id FROM categories WHERE slug = 'legumes'), 6.00, 'kg', 'Blettes fraîches avec tiges', 'Maroc', true),
('Fenouil', 'fenouil', (SELECT id FROM categories WHERE slug = 'legumes'), 12.00, 'kg', 'Fenouil parfumé et anisé', 'Maroc', true),
('Fève', 'feve', (SELECT id FROM categories WHERE slug = 'legumes'), 15.00, 'kg', 'Fèves fraîches du printemps', 'Maroc', true),
('Haricot Vert', 'haricot-vert', (SELECT id FROM categories WHERE slug = 'legumes'), 18.00, 'kg', 'Haricots verts fins et tendres', 'Maroc', true),
('Navet', 'navet', (SELECT id FROM categories WHERE slug = 'legumes'), 5.00, 'kg', 'Navets blancs et sucrés', 'Maroc', true),
('Oignon', 'oignon', (SELECT id FROM categories WHERE slug = 'legumes'), 4.00, 'kg', 'Oignons jaunes parfumés', 'Maroc', true),
('Oignon Rouge', 'oignon-rouge', (SELECT id FROM categories WHERE slug = 'legumes'), 6.00, 'kg', 'Oignons rouges doux', 'Maroc', true),
('Oignon Vert', 'oignon-vert', (SELECT id FROM categories WHERE slug = 'legumes'), 3.00, 'botte', 'Oignons verts frais', 'Maroc', true),
('Petits Pois', 'petits-pois', (SELECT id FROM categories WHERE slug = 'legumes'), 20.00, 'kg', 'Petits pois tendres et sucrés', 'Maroc', true),
('Poivron Doux', 'poivron-doux', (SELECT id FROM categories WHERE slug = 'legumes'), 12.00, 'kg', 'Poivrons doux multicolores', 'Maroc', true),
('Poivron Rouge', 'poivron-rouge', (SELECT id FROM categories WHERE slug = 'legumes'), 15.00, 'kg', 'Poivrons rouges sucrés', 'Maroc', true),
('Poivron Vert', 'poivron-vert', (SELECT id FROM categories WHERE slug = 'legumes'), 10.00, 'kg', 'Poivrons verts croquants', 'Maroc', true),
('Pomme de Terre Blanche', 'pomme-de-terre-blanche', (SELECT id FROM categories WHERE slug = 'legumes'), 3.50, 'kg', 'Pommes de terre blanches polyvalentes', 'Maroc', true),
('Pomme de Terre Petite', 'pomme-de-terre-petite', (SELECT id FROM categories WHERE slug = 'legumes'), 4.00, 'kg', 'Petites pommes de terre fondantes', 'Maroc', true),
('Pomme de Terre Rouge', 'pomme-de-terre-rouge', (SELECT id FROM categories WHERE slug = 'legumes'), 4.50, 'kg', 'Pommes de terre rouges savoureuses', 'Maroc', true),
('Pomme de Terre Frite', 'pomme-de-terre-frite', (SELECT id FROM categories WHERE slug = 'legumes'), 5.00, 'kg', 'Pommes de terre spéciales frites', 'Maroc', true),
('Topinambour', 'topinambour', (SELECT id FROM categories WHERE slug = 'legumes'), 8.00, 'kg', 'Topinambours croquants', 'Maroc', true),
('Tomate', 'tomate', (SELECT id FROM categories WHERE slug = 'legumes'), 9.00, 'kg', 'Tomates rouges juteuses', 'Maroc', true),
('Betterave', 'betterave', (SELECT id FROM categories WHERE slug = 'legumes'), 6.00, 'kg', 'Betteraves rouges sucrées', 'Maroc', true),

-- Fruits
('Ananas', 'ananas', (SELECT id FROM categories WHERE slug = 'fruits'), 25.00, 'pièce', 'Ananas tropical sucré', 'Maroc', true),
('Avocat', 'avocat', (SELECT id FROM categories WHERE slug = 'fruits'), 35.00, 'kg', 'Avocats onctueux et nutritifs', 'Maroc', true),
('Banane Importée', 'banane-importee', (SELECT id FROM categories WHERE slug = 'fruits'), 12.00, 'kg', 'Bananes importées mûres', 'Import', true),
('Banane Locale', 'banane-locale', (SELECT id FROM categories WHERE slug = 'fruits'), 15.00, 'kg', 'Bananes locales savoureuses', 'Maroc', true),
('Citron', 'citron', (SELECT id FROM categories WHERE slug = 'fruits'), 8.00, 'kg', 'Citrons jaunes juteux', 'Maroc', true),
('Fraise', 'fraise', (SELECT id FROM categories WHERE slug = 'fruits'), 40.00, 'kg', 'Fraises rouges parfumées', 'Maroc', true),
('Kaki', 'kaki', (SELECT id FROM categories WHERE slug = 'fruits'), 18.00, 'kg', 'Kakis doux et sucrés', 'Maroc', true),
('Kiwi', 'kiwi', (SELECT id FROM categories WHERE slug = 'fruits'), 30.00, 'kg', 'Kiwis verts vitaminés', 'Import', true),
('Mangue', 'mangue', (SELECT id FROM categories WHERE slug = 'fruits'), 35.00, 'kg', 'Mangues tropicales sucrées', 'Import', true),
('Orange Clémentine', 'orange-clementine', (SELECT id FROM categories WHERE slug = 'fruits'), 6.00, 'kg', 'Clémentines douces et faciles à éplucher', 'Maroc', true),
('Orange Navel', 'orange-navel', (SELECT id FROM categories WHERE slug = 'fruits'), 5.00, 'kg', 'Oranges Navel juteuses', 'Maroc', true),
('Orange à Jus', 'orange-a-jus', (SELECT id FROM categories WHERE slug = 'fruits'), 4.00, 'kg', 'Oranges parfaites pour le jus', 'Maroc', true),
('Poire', 'poire', (SELECT id FROM categories WHERE slug = 'fruits'), 20.00, 'kg', 'Poires fondantes et sucrées', 'Maroc', true),
('Pomme Importée', 'pomme-importee', (SELECT id FROM categories WHERE slug = 'fruits'), 18.00, 'kg', 'Pommes importées croquantes', 'Import', true),
('Pomme Locale Grand Calibre', 'pomme-locale-grand', (SELECT id FROM categories WHERE slug = 'fruits'), 15.00, 'kg', 'Pommes locales grand calibre', 'Maroc', true),
('Pomme Locale Moyen Calibre', 'pomme-locale-moyen', (SELECT id FROM categories WHERE slug = 'fruits'), 12.00, 'kg', 'Pommes locales moyen calibre', 'Maroc', true),
('Pomme Douce', 'pomme-douce', (SELECT id FROM categories WHERE slug = 'fruits'), 16.00, 'kg', 'Pommes douces et parfumées', 'Maroc', true),

-- Salades
('Batavia Rouge', 'batavia-rouge', (SELECT id FROM categories WHERE slug = 'salades'), 4.00, 'pièce', 'Salade batavia rouge croquante', 'Maroc', true),
('Batavia Verte', 'batavia-verte', (SELECT id FROM categories WHERE slug = 'salades'), 3.50, 'pièce', 'Salade batavia verte fraîche', 'Maroc', true),
('Chêne Vert', 'chene-vert', (SELECT id FROM categories WHERE slug = 'salades'), 4.50, 'pièce', 'Salade feuille de chêne verte', 'Maroc', true),
('Chêne Rouge', 'chene-rouge', (SELECT id FROM categories WHERE slug = 'salades'), 5.00, 'pièce', 'Salade feuille de chêne rouge', 'Maroc', true),
('Céleri-rave', 'celeri-rave', (SELECT id FROM categories WHERE slug = 'salades'), 8.00, 'kg', 'Céleri-rave pour salades', 'Maroc', true),
('Germes Alfalfa', 'germes-alfalfa', (SELECT id FROM categories WHERE slug = 'salades'), 15.00, 'barquette', 'Germes d''alfalfa croquants', 'Maroc', true),
('Germes Betterave', 'germes-betterave', (SELECT id FROM categories WHERE slug = 'salades'), 15.00, 'barquette', 'Germes de betterave colorés', 'Maroc', true),
('Germes Poireau', 'germes-poireau', (SELECT id FROM categories WHERE slug = 'salades'), 15.00, 'barquette', 'Germes de poireau parfumés', 'Maroc', true),
('Iceberg', 'iceberg', (SELECT id FROM categories WHERE slug = 'salades'), 3.00, 'pièce', 'Salade iceberg croquante', 'Maroc', true),
('Laitue Romaine', 'laitue-romaine', (SELECT id FROM categories WHERE slug = 'salades'), 3.00, 'pièce', 'Laitue romaine ferme', 'Maroc', true),
('Laitue Rouge', 'laitue-rouge', (SELECT id FROM categories WHERE slug = 'salades'), 4.00, 'pièce', 'Laitue rouge décorative', 'Maroc', true),
('Laitue Verte', 'laitue-verte', (SELECT id FROM categories WHERE slug = 'salades'), 2.50, 'pièce', 'Laitue verte classique', 'Maroc', true),
('Lollo Rouge', 'lollo-rouge', (SELECT id FROM categories WHERE slug = 'salades'), 4.50, 'pièce', 'Salade lollo rouge frisée', 'Maroc', true),
('Mesclun', 'mesclun', (SELECT id FROM categories WHERE slug = 'salades'), 25.00, 'kg', 'Mélange de jeunes pousses', 'Maroc', true),
('Mâche', 'mache', (SELECT id FROM categories WHERE slug = 'salades'), 30.00, 'kg', 'Mâche tendre et douce', 'Maroc', true),
('Pousses Betterave', 'pousses-betterave', (SELECT id FROM categories WHERE slug = 'salades'), 20.00, 'kg', 'Pousses de betterave tendres', 'Maroc', true),
('Pousses Épinard', 'pousses-epinard', (SELECT id FROM categories WHERE slug = 'salades'), 18.00, 'kg', 'Pousses d''épinard baby', 'Maroc', true),
('Roquette', 'roquette', (SELECT id FROM categories WHERE slug = 'salades'), 25.00, 'kg', 'Roquette piquante et aromatique', 'Maroc', true),
('Salade Frisée', 'salade-frisee', (SELECT id FROM categories WHERE slug = 'salades'), 3.50, 'pièce', 'Salade frisée croquante', 'Maroc', true),
('Tomates Cerises', 'tomates-cerises', (SELECT id FROM categories WHERE slug = 'salades'), 20.00, 'kg', 'Tomates cerises sucrées', 'Maroc', true),

-- Herbes
('Aneth', 'aneth', (SELECT id FROM categories WHERE slug = 'herbes'), 5.00, 'botte', 'Aneth frais parfumé', 'Maroc', true),
('Basilic', 'basilic', (SELECT id FROM categories WHERE slug = 'herbes'), 6.00, 'botte', 'Basilic vert aromatique', 'Maroc', true),
('Céleri', 'celeri', (SELECT id FROM categories WHERE slug = 'herbes'), 4.00, 'botte', 'Céleri branche parfumé', 'Maroc', true),
('Ciboulette', 'ciboulette', (SELECT id FROM categories WHERE slug = 'herbes'), 4.00, 'botte', 'Ciboulette fraîche et fine', 'Maroc', true),
('Coriandre', 'coriandre', (SELECT id FROM categories WHERE slug = 'herbes'), 2.00, 'botte', 'Coriandre fraîche parfumée', 'Maroc', true),
('Mauve des Bois', 'mauve-des-bois', (SELECT id FROM categories WHERE slug = 'herbes'), 8.00, 'botte', 'Mauve sauvage des bois', 'Maroc', true),
('Menthe', 'menthe', (SELECT id FROM categories WHERE slug = 'herbes'), 2.50, 'botte', 'Menthe fraîche rafraîchissante', 'Maroc', true),
('Persil', 'persil', (SELECT id FROM categories WHERE slug = 'herbes'), 1.50, 'botte', 'Persil plat ou frisé', 'Maroc', true),
('Romarin', 'romarin', (SELECT id FROM categories WHERE slug = 'herbes'), 5.00, 'botte', 'Romarin aromatique', 'Maroc', true),
('Thym', 'thym', (SELECT id FROM categories WHERE slug = 'herbes'), 4.00, 'botte', 'Thym frais parfumé', 'Maroc', true)
ON CONFLICT (slug) DO NOTHING;