// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpgbosskktozsvfwnvzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwZ2Jvc3Nra3RvenN2ZndudnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDgzNzUsImV4cCI6MjA3MDkyNDM3NX0.O1TUfUP4rPcwiY68F7GslLNa9tOlFkH_0Zbp3NfbJq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});